Update objective functions in dscore_reward.py
molecule-generator-collection/ChemTSv2 pull request #6
Opened 2021-11-22 01:29 UTC by tyszw

`dscore_reward.py`の目的関数を更新しました。

2021-11-22 05:28 UTC, sishida21 requested changes

2021-11-22 05:28 UTC, sishida21 commented on reward/dscore_reward.py
> +def scale_objective_values(target_name, value, conf):
処理している値は一つなので `scale_objective_value` にしてください。

2021-11-22 05:28 UTC, sishida21 commented on reward/dscore_reward.py
> +    scaled_values = []
ここのscaling、部分的にループ回すのはどの値にどういうscalingをしているかがわかりにくいので、冗長でも良いので一つ一つ書いてください。そうすれば統一感も出て読みやすいです。

2021-11-22 05:28 UTC, sishida21 commented on reward/dscore_reward.py
> +def scale_objective_values(target_name, value, conf):
下のコメントに対応する際にこの関数は不要になるかもですね

2021-11-25 09:29 UTC, tyszw commented
aad749792cd3ed210dfd3ab87aa85fafcd52206c で対応しました。ご確認よろしくお願い致します。

2021-11-26 07:54 UTC, sishida21 approved these changes

2021-11-26 07:54 UTC, merged